name: Deploy Lambda Function

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - name: user-create
            path: lambda-functions/user-create
            arn: arn:aws:lambda:ap-south-1:202533533974:function:Test_Lambda_Function
          - name: user-delete
            path: lambda-functions/user-delete
            arn: arn:aws:lambda:ap-south-1:202533533974:function:Lambda_Function2

    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Zip and Deploy Lambda
        run: |
          cd ${{ matrix.path }}
          zip -r ${{ matrix.name }}.zip.
          cd ../..
          aws lambda update-function-code \
            --function-name ${{ matrix.arn }} \
            --zip-file fileb://${{ matrix.name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"

