name: Deploy Lambda Function

on:
  push:
    branches: [ master ]

strategy:
  matrix:
    function:
      - name: FunctionA
        path: lambda-functions/user-create
        arn: arn:aws:lambda:ap-south-1:202533533974:function:Test_Lambda_Function
      - name: FunctionB
        path: lambda-functions/user-delete
        arn: arn:aws:lambda:ap-south-1:202533533974:function:Lambda_Function2

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - run: zip -r code.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function.arn }} \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"

